from __future__ import annotations

import re
from pathlib import Path


def replace_regex_once(text: str, pattern: str, replacement: str, label: str, flags: int = re.DOTALL) -> str:
    updated, count = re.subn(pattern, replacement, text, count=1, flags=flags)
    if count != 1:
        raise RuntimeError(f"{label}: expected exactly one match, found {count}")
    return updated


def patch_interpreter(root: Path) -> None:
    path = root / "libultraship/src/fast/interpreter.cpp"
    text = path.read_text(encoding="utf-8")

    # The validation code below uses the standard C++ finite/fabs overloads. Keep this idempotent because
    # Actions may be re-run against a workspace that has already passed through this script.
    if "#include <cmath> // dynamic-shadow validation" not in text:
        if "#include <math.h>\n" not in text:
            raise RuntimeError("interpreter include insertion: #include <math.h> was not found")
        text = text.replace(
            "#include <math.h>\n",
            "#include <math.h>\n#include <cmath> // dynamic-shadow validation\n",
            1,
        )

    if "kMaxShadowTriangleEdge" not in text:
        validated_lambda = r'''        auto appendShadowTriangle = [this](float ax, float ay, float az, float bx, float by, float bz, float cx,
                                            float cy, float cz) {
            // Reject malformed replacement-model geometry before it can rasterize a triangle across the
            // complete shadow cascade. This prevents the giant diagonal/rectangular black bands seen in-game.
            if (!std::isfinite(ax) || !std::isfinite(ay) || !std::isfinite(az) || !std::isfinite(bx) ||
                !std::isfinite(by) || !std::isfinite(bz) || !std::isfinite(cx) || !std::isfinite(cy) ||
                !std::isfinite(cz)) {
                return;
            }

            constexpr float kMaxShadowCasterRadius = 1536.0f;
            constexpr float kMaxShadowCasterHeight = 3072.0f;
            constexpr float kMaxShadowTriangleEdge = 1536.0f;
            const float radiusSquared = kMaxShadowCasterRadius * kMaxShadowCasterRadius;
            const float edgeSquaredLimit = kMaxShadowTriangleEdge * kMaxShadowTriangleEdge;

            auto vertexInsideCascade = [&](float x, float y, float z) {
                const float dx = x - mDynamicShadowAnchor[0];
                const float dy = y - mDynamicShadowAnchor[1];
                const float dz = z - mDynamicShadowAnchor[2];
                return (dx * dx + dz * dz) <= radiusSquared && std::fabs(dy) <= kMaxShadowCasterHeight;
            };
            if (!vertexInsideCascade(ax, ay, az) || !vertexInsideCascade(bx, by, bz) ||
                !vertexInsideCascade(cx, cy, cz)) {
                return;
            }

            auto edgeLengthSquared = [](float x0, float y0, float z0, float x1, float y1, float z1) {
                const float dx = x1 - x0;
                const float dy = y1 - y0;
                const float dz = z1 - z0;
                return dx * dx + dy * dy + dz * dz;
            };
            if (edgeLengthSquared(ax, ay, az, bx, by, bz) > edgeSquaredLimit ||
                edgeLengthSquared(bx, by, bz, cx, cy, cz) > edgeSquaredLimit ||
                edgeLengthSquared(cx, cy, cz, ax, ay, az) > edgeSquaredLimit) {
                return;
            }

            const float abx = bx - ax;
            const float aby = by - ay;
            const float abz = bz - az;
            const float acx = cx - ax;
            const float acy = cy - ay;
            const float acz = cz - az;
            const float crossX = aby * acz - abz * acy;
            const float crossY = abz * acx - abx * acz;
            const float crossZ = abx * acy - aby * acx;
            if (crossX * crossX + crossY * crossY + crossZ * crossZ < 0.0001f) {
                return;
            }

            mShadowVerts.push_back(ax);
            mShadowVerts.push_back(ay);
            mShadowVerts.push_back(az);
            mShadowVerts.push_back(bx);
            mShadowVerts.push_back(by);
            mShadowVerts.push_back(bz);
            mShadowVerts.push_back(cx);
            mShadowVerts.push_back(cy);
            mShadowVerts.push_back(cz);
        };'''

        # Match the small append lambda structurally instead of requiring the exact indentation generated by
        # apply_realistic_shadow_fixes.py. The old strict text match caused run 30140715117 to fail here.
        text = replace_regex_once(
            text,
            r"        auto appendShadowTriangle = \[this\]\(float ax, float ay, float az, float bx, float by, float bz, float cx,\s*\n\s*float cy, float cz\) \{.*?\n        \};",
            validated_lambda,
            "shadow triangle validation",
        )

    if "The map now contains only explicitly armed actor geometry" not in text:
        actor_only_render = r'''    // Finish room capture, but do not use camera-visible room triangles as shadow casters. Their set changes
    // whenever the camera turns, which made terrain shadows appear, disappear or form large diagonal bands.
    // The map now contains only explicitly armed actor geometry selected in stable world space around Link.
    mCaptureEnvironmentShadow = false;

    // Fast3D applies its widescreen correction to clip X after P_matrix. Pass the exact effective
    // matrix to the backend so reconstruction from the DX11 depth buffer cannot swim with camera rotation.
    float effectiveCamera[16];
    memcpy(effectiveCamera, &mRsp->P_matrix[0][0], sizeof(effectiveCamera));
    if (!mFbActive && mCurDimensions.width > 0 && mCurDimensions.height > 0) {
        const float targetAspect = static_cast<float>(mCurDimensions.width) / static_cast<float>(mCurDimensions.height);
        const float aspectScale = (4.0f / 3.0f) / targetAspect;
        for (int row = 0; row < 4; row++) {
            effectiveCamera[row * 4] *= aspectScale;
        }
    }

    const size_t vertexCount = mShadowCasterAccum.size() / 3;
    mRapi->RenderDynamicShadowMap(vertexCount >= 3 ? mShadowCasterAccum.data() : nullptr, vertexCount,
                                  effectiveCamera, mDynamicShadowLightDir, mDynamicShadowAnchor,
                                  mDynamicShadowLocalLight, kDynamicShadowMapResolution,
                                  std::clamp(mToonShadowAlpha, 0.0f, 1.0f), kDynamicShadowMapBias,
                                  kDynamicShadowMapPcfRadius);

    mEnvironmentShadowCasterAccum.clear();
    mShadowCasterAccum.clear();'''

        text = replace_regex_once(
            text,
            r"    // This command is emitted after the opaque room.*?\n    mEnvironmentShadowCasterAccum\.clear\(\);\n    mShadowCasterAccum\.clear\(\);",
            actor_only_render,
            "actor-only stable shadow map",
        )

    path.write_text(text, encoding="utf-8", newline="\n")


def patch_toon_lighting(root: Path) -> None:
    path = root / "soh/soh/Enhancements/Graphics/ToonLighting.cpp"
    text = path.read_text(encoding="utf-8")

    if "ZZNaviShadowLightFix.cpp is the only owner of the dynamic shadow-map state" not in text:
        text = replace_regex_once(
            text,
            r"    // Dynamic shadow mapping.*?\n    // Clear before any early-out",
            r'''    // ZZNaviShadowLightFix.cpp is the only owner of the dynamic shadow-map state. Keeping a second
    // SetDynamicShadowCaptureState call here made two unordered frame hooks compete over direction and Navi
    // state, producing frame-to-frame instability.

    // Clear before any early-out''',
            "single shadow-map state owner",
        )

    if "ZZNaviShadowLightFix.cpp exclusively owns caster arming" not in text:
        text = replace_regex_once(
            text,
            r"    // Actor shadow: arm this actor as a dynamic shadow-map caster\..*?\n    if \(sParams\.showDebug\)",
            r'''    // ZZNaviShadowLightFix.cpp exclusively owns caster arming and world-space range hysteresis.
    // The duplicate camera/frustum-dependent arming path that used to live here was intentionally removed.

    if (sParams.showDebug)''',
            "single shadow caster policy",
        )

    path.write_text(text, encoding="utf-8", newline="\n")


def patch_actor_draw_order(root: Path) -> None:
    path = root / "soh/src/code/z_actor.c"
    text = path.read_text(encoding="utf-8")

    if "Navi's pool was the large circular ball on the ground" not in text:
        text = replace_regex_once(
            text,
            r"^[ \t]*GameInteractor_ExecuteOnPlayDrawWorldLights\(play\);[ \t]*$",
            r'''    // Point lights, including Navi, continue to affect actor toon lighting through ToonLighting.cpp.
    // Do not draw the old world-space light pool: Navi's pool was the large circular ball on the ground.''',
            "remove Navi ground light pool",
            flags=re.MULTILINE,
        )

    if "Resolve the shadow map after opaque actors" not in text:
        text = replace_regex_once(
            text,
            r"\n    if \(shadowsEnabled\) \{\n        gSPToonShadowFlush\(POLY_OPA_DISP\+\+\);\n    \}\n\n    actorListEntry = &actorCtx->actorLists\[0\];",
            "\n    actorListEntry = &actorCtx->actorLists[0];",
            "remove pre-actor shadow resolve",
        )

        text = replace_regex_once(
            text,
            r"    \}\n\n    // SOH \[Enhancement\] Toon lighting: end the actor bracket before effects/lens/UI are drawn\.",
            r'''    }

    if (shadowsEnabled) {
        // Resolve the shadow map after opaque actors have written depth. Link and other solid actors now receive
        // cast shadows. Navi remains in the later translucent stream and is never submitted as a caster.
        gSPToonShadowFlush(POLY_OPA_DISP++);
    }

    // SOH [Enhancement] Toon lighting: end the actor bracket before effects/lens/UI are drawn.''',
            "post-actor shadow resolve",
        )

    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    patch_interpreter(root)
    patch_toon_lighting(root)
    patch_actor_draw_order(root)
    print(
        "Applied actor-only camera-independent shadows, invalid-triangle rejection, post-actor receiving, "
        "and removed Navi's ground light pool."
    )


if __name__ == "__main__":
    main()
