from __future__ import annotations

from pathlib import Path


def insert_after_once(text: str, marker: str, addition: str, label: str) -> str:
    index = text.find(marker)
    if index < 0:
        raise RuntimeError(f"{label}: marker not found")
    return text[: index + len(marker)] + addition + text[index + len(marker) :]


def replace_between(text: str, start_marker: str, end_marker: str, replacement: str, label: str) -> str:
    start = text.find(start_marker)
    if start < 0:
        raise RuntimeError(f"{label}: start marker not found")
    end = text.find(end_marker, start + len(start_marker))
    if end < 0:
        raise RuntimeError(f"{label}: end marker not found")
    return text[:start] + replacement + text[end:]


def patch_interpreter_header(root: Path) -> None:
    path = root / "libultraship/include/fast/interpreter.h"
    text = path.read_text(encoding="utf-8")

    if "mNaviShadowCasterAccum" not in text:
        marker = "    std::vector<float> mShadowCasterAccum;"
        addition = '''
    // Compact casters close enough to a visible Navi. These receive a dedicated shadow-map pass
    // whose projection direction points toward Navi instead of using the sun/moon direction.
    std::vector<float> mNaviShadowCasterAccum;
    float mNaviShadowCasterCenterSum[3] = { 0.0f, 0.0f, 0.0f };
    uint32_t mNaviShadowCasterCount = 0;'''
        text = insert_after_once(text, marker, addition, "Navi-directed compact caster state")

    # SetDynamicShadowCaptureState(false, ...) owns the persistent cleanup. Insert beside the existing actor
    # accumulator clear without depending on the exact comments or spacing generated by earlier scripts.
    if "mNaviShadowCasterAccum.clear();" not in text:
        disabled = text.find("if (!enabled)")
        if disabled < 0:
            raise RuntimeError("Navi-directed caster disable cleanup: disabled-state block not found")
        actor_clear = text.find("mShadowCasterAccum.clear();", disabled)
        if actor_clear < 0:
            raise RuntimeError("Navi-directed caster disable cleanup: actor clear not found")
        line_end = text.find("\n", actor_clear)
        if line_end < 0:
            raise RuntimeError("Navi-directed caster disable cleanup: actor clear line end not found")
        indent_start = text.rfind("\n", 0, actor_clear) + 1
        indent = text[indent_start:actor_clear]
        cleanup = (
            f"\n{indent}mNaviShadowCasterAccum.clear();"
            f"\n{indent}mNaviShadowCasterCenterSum[0] = 0.0f;"
            f"\n{indent}mNaviShadowCasterCenterSum[1] = 0.0f;"
            f"\n{indent}mNaviShadowCasterCenterSum[2] = 0.0f;"
            f"\n{indent}mNaviShadowCasterCount = 0;"
        )
        text = text[:line_end] + cleanup + text[line_end:]

    path.write_text(text, encoding="utf-8", newline="\n")


def patch_interpreter(root: Path) -> None:
    path = root / "libultraship/src/fast/interpreter.cpp"
    text = path.read_text(encoding="utf-8")

    flush_start = "void Interpreter::FlushToonShadow() {"
    render_start = "void Interpreter::RenderShadowVolumes() {"
    flush = r'''void Interpreter::FlushToonShadow() {
    const float coreAlpha = std::clamp(mToonShadowAlpha, 0.0f, 1.0f);
    if (mShadowVerts.size() < 9 || coreAlpha <= 0.0f || !mRdp->toon_shadow) {
        mShadowVerts.clear();
        return;
    }

    // Classify the complete current object by its world-space bounds. Large actors keep the environment
    // direction. A compact actor close to a visible Navi is routed to a separate pass so the fairy becomes
    // the actual shadow-light direction instead of merely bleaching the existing sun/moon shadow.
    float minimum[3] = { mShadowVerts[0], mShadowVerts[1], mShadowVerts[2] };
    float maximum[3] = { minimum[0], minimum[1], minimum[2] };
    for (size_t offset = 3; offset + 2 < mShadowVerts.size(); offset += 3) {
        minimum[0] = std::min(minimum[0], mShadowVerts[offset + 0]);
        minimum[1] = std::min(minimum[1], mShadowVerts[offset + 1]);
        minimum[2] = std::min(minimum[2], mShadowVerts[offset + 2]);
        maximum[0] = std::max(maximum[0], mShadowVerts[offset + 0]);
        maximum[1] = std::max(maximum[1], mShadowVerts[offset + 1]);
        maximum[2] = std::max(maximum[2], mShadowVerts[offset + 2]);
    }

    constexpr float kLargeLocalLightCasterExtent = 240.0f;
    const bool largeCaster = maximum[0] - minimum[0] > kLargeLocalLightCasterExtent ||
                             maximum[1] - minimum[1] > kLargeLocalLightCasterExtent ||
                             maximum[2] - minimum[2] > kLargeLocalLightCasterExtent;

    const float center[3] = {
        (minimum[0] + maximum[0]) * 0.5f,
        (minimum[1] + maximum[1]) * 0.5f,
        (minimum[2] + maximum[2]) * 0.5f,
    };
    constexpr float kNaviDirectionInfluenceRadius = 220.0f;
    const float publishedRadius = std::fabs(mDynamicShadowLocalLight[3]);
    const float naviRadius = std::min(publishedRadius, kNaviDirectionInfluenceRadius);
    const float naviDx = center[0] - mDynamicShadowLocalLight[0];
    const float naviDy = center[1] - mDynamicShadowLocalLight[1];
    const float naviDz = center[2] - mDynamicShadowLocalLight[2];
    const float halfExtentX = (maximum[0] - minimum[0]) * 0.5f;
    const float halfExtentY = (maximum[1] - minimum[1]) * 0.5f;
    const float halfExtentZ = (maximum[2] - minimum[2]) * 0.5f;
    const float actorHalfExtent = std::max(halfExtentX, std::max(halfExtentY, halfExtentZ));
    const float effectiveNaviRadius = naviRadius + std::min(actorHalfExtent, 64.0f);
    const bool naviDirectedCaster = !largeCaster && naviRadius > 0.0f &&
                                    naviDx * naviDx + naviDy * naviDy + naviDz * naviDz <=
                                        effectiveNaviRadius * effectiveNaviRadius;

    std::vector<float>& destination = largeCaster
                                          ? mLargeShadowCasterAccum
                                          : (naviDirectedCaster ? mNaviShadowCasterAccum : mShadowCasterAccum);

    const size_t available = destination.size() < kShadowAccumBudgetFloats
                                 ? kShadowAccumBudgetFloats - destination.size()
                                 : 0;
    const size_t copyFloats = std::min(mShadowVerts.size(), available - (available % 9));
    if (copyFloats >= 9) {
        destination.insert(destination.end(), mShadowVerts.begin(), mShadowVerts.begin() + copyFloats);
        if (naviDirectedCaster) {
            mNaviShadowCasterCenterSum[0] += center[0];
            mNaviShadowCasterCenterSum[1] += center[1];
            mNaviShadowCasterCenterSum[2] += center[2];
            ++mNaviShadowCasterCount;
        }
    }

    mShadowVerts.clear();
}

'''
    text = replace_between(
        text,
        flush_start,
        render_start,
        flush,
        "compact caster routing by Navi distance",
    )

    compact_start = "    // Resolve compact dynamic actors separately"
    compact_end_line = "    mLargeShadowCasterAccum.clear();"
    compact_start_index = text.find(compact_start, text.find(render_start))
    if compact_start_index < 0:
        raise RuntimeError("Navi-directed compact shadow resolve: compact resolve marker not found")
    compact_end_index = text.find(compact_end_line, compact_start_index)
    if compact_end_index < 0:
        raise RuntimeError("Navi-directed compact shadow resolve: large-caster clear not found")
    compact_end_index += len(compact_end_line)

    compact_resolve = r'''    // Compact actors outside Navi's small influence radius retain the stable environmental direction.
    // No local-fill radius is supplied: distant actors must not brighten merely because Navi exists elsewhere.
    const float noLocalFill[4] = { 0.0f, 0.0f, 0.0f, 0.0f };
    if (mShadowCasterAccum.size() >= 9) {
        const size_t actorVertexCount = mShadowCasterAccum.size() / 3;
        mRapi->RenderDynamicShadowMap(
            mShadowCasterAccum.data(), actorVertexCount, effectiveCamera, mDynamicShadowLightDir,
            mDynamicShadowAnchor, noLocalFill, kDynamicShadowMapResolution,
            std::clamp(mToonShadowAlpha, 0.0f, 1.0f), kDynamicShadowMapBias, kDynamicShadowMapPcfRadius);
    }

    // For compact actors close to a visible Navi, the fairy becomes the primary light direction. The average
    // caster centre keeps one inexpensive directional pass coherent for Link and nearby small actors.
    if (mNaviShadowCasterAccum.size() >= 9 && mNaviShadowCasterCount > 0 && mDynamicShadowLocalLight[3] > 0.0f) {
        const float inverseCasterCount = 1.0f / static_cast<float>(mNaviShadowCasterCount);
        const float casterCenter[3] = {
            mNaviShadowCasterCenterSum[0] * inverseCasterCount,
            mNaviShadowCasterCenterSum[1] * inverseCasterCount,
            mNaviShadowCasterCenterSum[2] * inverseCasterCount,
        };
        float naviLightDirection[3] = {
            mDynamicShadowLocalLight[0] - casterCenter[0],
            mDynamicShadowLocalLight[1] - casterCenter[1],
            mDynamicShadowLocalLight[2] - casterCenter[2],
        };
        float directionLengthSquared = naviLightDirection[0] * naviLightDirection[0] +
                                       naviLightDirection[1] * naviLightDirection[1] +
                                       naviLightDirection[2] * naviLightDirection[2];
        if (directionLengthSquared > 0.000001f) {
            const float inverseLength = 1.0f / std::sqrt(directionLengthSquared);
            naviLightDirection[0] *= inverseLength;
            naviLightDirection[1] *= inverseLength;
            naviLightDirection[2] *= inverseLength;

            constexpr float kMinimumNaviElevation = 0.25f;
            if (naviLightDirection[1] < kMinimumNaviElevation) {
                const float horizontalLength = std::sqrt(naviLightDirection[0] * naviLightDirection[0] +
                                                         naviLightDirection[2] * naviLightDirection[2]);
                const float horizontalTarget = std::sqrt(1.0f - kMinimumNaviElevation * kMinimumNaviElevation);
                if (horizontalLength > 0.00001f) {
                    const float horizontalScale = horizontalTarget / horizontalLength;
                    naviLightDirection[0] *= horizontalScale;
                    naviLightDirection[2] *= horizontalScale;
                } else {
                    naviLightDirection[0] = horizontalTarget;
                    naviLightDirection[2] = 0.0f;
                }
                naviLightDirection[1] = kMinimumNaviElevation;
            }
        } else {
            naviLightDirection[0] = mDynamicShadowLightDir[0];
            naviLightDirection[1] = mDynamicShadowLightDir[1];
            naviLightDirection[2] = mDynamicShadowLightDir[2];
        }

        const size_t naviActorVertexCount = mNaviShadowCasterAccum.size() / 3;
        mRapi->RenderDynamicShadowMap(
            mNaviShadowCasterAccum.data(), naviActorVertexCount, effectiveCamera, naviLightDirection,
            mDynamicShadowAnchor, noLocalFill, kDynamicShadowMapResolution,
            std::clamp(mToonShadowAlpha, 0.0f, 1.0f), kDynamicShadowMapBias, kDynamicShadowMapPcfRadius);
    }

    mShadowCasterAccum.clear();
    mNaviShadowCasterAccum.clear();
    mLargeShadowCasterAccum.clear();
    mNaviShadowCasterCenterSum[0] = 0.0f;
    mNaviShadowCasterCenterSum[1] = 0.0f;
    mNaviShadowCasterCenterSum[2] = 0.0f;
    mNaviShadowCasterCount = 0;'''

    text = text[:compact_start_index] + compact_resolve + text[compact_end_index:]
    path.write_text(text, encoding="utf-8", newline="\n")


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    patch_interpreter_header(root)
    patch_interpreter(root)
    print(
        "Routed compact nearby actors to a Navi-directed shadow pass; world, large and distant casters keep environment direction."
    )


if __name__ == "__main__":
    main()
